# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
#    filters: # only run on PR
#      branches:
#        ignore:
#          - main
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-2-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
            - ~/.local/share/pnpm/store/v3
      - run:
          command: pnpm store path
          name: confirm pnpm store
      - run:
          command: ./scripts/test-all.sh
          name: Build & Test All
      - run:
          command: pnpm lint
          name: Lint
#      - persist_to_workspace:
#          root: ~/project
#          paths:
#            - .

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  ci: # This is the name of the workflow, feel free to change it to better match your workflow.
  # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build_and_test