name: docs

on:
  push:
    tags:
      - v**
permissions:
  contents: write

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn install

      - name: Create the docs directory locally in CI
        run: yarn gen && yarn docs
        working-directory: sdk

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: sdk/docs