name: Publish SDK & CLI

on:
  push:
    branches:
      - main
      - release
      - v1
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.event.inputs.commit }}
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Build SDK & CLI
        run: pnpm --filter "./packages/*..." build
      - name: Set NPM credential
        id: npm
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc

          DIST_TAG=latest
          if [[ "${{ contains(steps.semantic.outputs.new_release_version, '-rc.') }}" == "true" ]]; then          
            DIST_TAG=rc
          fi
          echo "dist_tag=${DIST_TAG}" >> $GITHUB_OUTPUT
      - name: SDK Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: SDK Release Summary
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo "### New SDK version v${{ steps.semantic.outputs.new_release_version }} cut" >> $GITHUB_STEP_SUMMARY
          echo "commit: ${GITHUB_SHA}, branch/tag: ${GITHUB_REF}" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.semantic.outputs.new_release_notes }}" >> $GITHUB_STEP_SUMMARY
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: SDK NPM Publish
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          ./scripts/update-version.sh @sentio/sdk... ${{ steps.semantic.outputs.new_release_version }}
          pnpm publish --filter "@sentio/sdk..." --no-git-checks --tag ${{ steps.npm.outputs.dist_tag }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: report error
        if: steps.semantic.outputs.new_release_published == 'false'
        run: |
          echo "### No SDK version cut" >> $GITHUB_STEP_SUMMARY
          echo "Check Semantic Release output for details"
      - name: Clean templates node modules
        run: "rm -rf */node_modules"
        working-directory: packages/cli/templates
      - name: CLI Semantic Release
        id: semantic_cli
        uses: cycjimmy/semantic-release-action@v3
        with:
          working_directory: packages/cli
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: CLI Release Summary
        if: steps.semantic_cli.outputs.new_release_published == 'true'
        run: |
          echo "### New CLI version v${{ steps.semantic_cli.outputs.new_release_version }} cut" >> $GITHUB_STEP_SUMMARY
          echo "commit: ${GITHUB_SHA}, branch/tag: ${GITHUB_REF}" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.semantic_cli.outputs.new_release_notes }}" >> $GITHUB_STEP_SUMMARY
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: CLI NPM Publish
        if: steps.semantic_cli.outputs.new_release_published == 'true'
        run: |
          ./scripts/update-version.sh @sentio/cli ${{ steps.semantic_cli.outputs.new_release_version }}
          pnpm publish --filter "@sentio/cli" --no-git-checks --tag ${{ steps.npm.outputs.dist_tag }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: report error
        if: steps.semantic.outputs.new_release_published == 'false'
        run: |
          echo "### No CLI version cut" >> $GITHUB_STEP_SUMMARY
          echo "Check Semantic Release output for details"
      - name: Clean Github Release for RC
        if: contains(steps.semantic.outputs.new_release_version, '-rc.')
        run:  ./scripts/clean-rc-releases.sh
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
