name: Publish SDK

on:
  push:
    branches:
      - main
      - release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.event.inputs.commit }}
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build_all
        working-directory: packages/sdk
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
#        with:
#          working_directory: packages/sdk
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Make Release Summary
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo "### New version v${{ steps.semantic.outputs.new_release_version }} cut" >> $GITHUB_STEP_SUMMARY
          echo "commit: ${GITHUB_SHA}, branch/tag: ${GITHUB_REF}" >> $GITHUB_STEP_SUMMARY
          echo "automatic release will be marked as prerelease, please manually confirm in the release page" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.semantic.outputs.new_release_notes }}" >> $GITHUB_STEP_SUMMARY
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: report error
        if: steps.semantic.outputs.new_release_published == 'false'
        run: |
          echo "### No version cut" >> $GITHUB_STEP_SUMMARY
          echo "Check Semantic Release output for details"
          exit(1)
      - name: Lerna Publish
        run: |
          DIST_TAG=latest
          if [[ "${{ contains(steps.semantic.outputs.new_release_version, '-rc.') }}" == "true" ]]; then          
            DIST_TAG=rc
          fi
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
          yarn lerna publish ${{ steps.semantic.outputs.new_release_version }} --no-private --yes --no-push --no-git-tag-version --dist-tag $DIST_TAG
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      release_version: ${{ steps.release.outputs.release_version }}
