name: Publish Docs

on:
  push:
    tags:
      - v**
      - "!v**-rc**"
permissions:
  contents: write

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn install
      - name: Build
        run: yarn lerna run build --no-private --ignore @sentio/sdk-all
      - name: Create the docs directory locally in CI
        run: yarn docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs