name: Release

on:
  push:
    branches:
      - main
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
        working-directory: sdk
      - name: Release
        id: release
        run: yarn semantic-release
        working-directory: sdk
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      release_version: ${{ steps.release.outputs.release_version }}